### PR TITLE
ran swift 4 migration

### PR DESCRIPTION
**Pull request by cgossain**
Used the “Minimize Inference” option.

### CODE REVIEW

**Comment by totocaster** [comment]
Hi, thanks for the PR! There is one from 7 days ago that addresses the same issue. Please feel free to contribute to [that PR](https://github.com/totocaster/Typist/pull/13).

**Comment by cgossain** [comment]
Hi yes I did notice the other PR. However I noticed that the changes were broader than what the PR title claimed. I submitted this PR because it's focused to the Swift 4 migration only. I figured it might be merged faster. Thanks anyways.

**Comment by totocaster** [comment]
I had no chance to have a look into any PRs before, sorry about that. New Typist 1.1.0 is released with Swift 4 and iPhone X support. Thanks again for the PR.

**Comment by cgossain** [comment]
Hi, ya no worries, I love this library, so glad Swift 4 migration is good to go now. I have this as a dependency to some of my other pods and just love it. Thanks!

**Pull request closed without merging**
