### PR TITLE
Raise Keyboard Options Access Level From Internal to Public

### PR DESCRIPTION
**Pull request by TosinAF**
Had issues accessing the keyboard options properties as they were internal.

This PR makes their access control public.

### CODE REVIEW

**Comment by totocaster** [comment]
Hey Tosin, thanks for PR! Did this happen using Carthage?

**Comment by totocaster** [comment]
Merged. Thanks again!

**Comment by TosinAF** [comment]
Nah, It was with Pods. Thanks for the quick merge and sick library man.

I forced myself to update my project to Swift 3 just so i could use this library. It's perfect.

**Comment by totocaster** [comment]
Happy to hear that! Thank you!

**Pull request merged**
